create table if not exists public.test_items (
	id bigint generated by default as identity primary key,
	name text not null,
	created_at timestamptz not null default now()
);

alter table public.test_items enable row level security;

create policy "Allow read for anon"
on public.test_items
for select
to anon
using (true);

create policy "Allow insert for anon"
on public.test_items
for insert
to anon
with check (true);
